#!/bin/bash

sudo apt-get install --yes --force-yes python-software-properties

echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -

echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O- | sudo apt-key add -

echo "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/dropbox.list
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E

sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

sudo add-apt-repository -y ppa:scopes-packagers/ppa
sudo add-apt-repository -y ppa:leolik/leolik
sudo add-apt-repository -y ppa:nilarimogard/webupd8

sudo apt-get update

sudo apt-get dist-upgrade
