#!/bin/bash

# Show status bar on nautilus
gsettings set org.gnome.nautilus.window-state start-with-status-bar true

# Auto hide launcher
gsettings set com.canonical.Unity2d.Launcher hide-mode 1

# Touchpad
gsettings set org.gnome.settings-daemon.peripherals.touchpad scroll-method 'two-finger-scrolling'
gsettings set org.gnome.settings-daemon.peripherals.touchpad horiz-scroll-enabled true

# Date & Time indicator
gsettings set com.canonical.indicator.datetime show-date true
gsettings set com.canonical.indicator.datetime show-day true
