#!/bin/bash

sudo apt-get install --yes --force-yes python-software-properties

if ! [ -f /etc/apt/sources.list.d/virtualbox.list ]; then
  wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
fi

if ! [ -f /etc/apt/sources.list.d/google-chrome.list ]; then
  wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O- | sudo apt-key add -
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
fi

if ! [ -f /etc/apt/sources.list.d/dropbox.list ]; then
  echo "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/dropbox.list
  sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
fi

# Skype
sudo add-apt-repository -y "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

# Custom notify-osd
sudo add-apt-repository -y ppa:leolik/leolik
sudo add-apt-repository -y ppa:nilarimogard/webupd8

sudo apt-get update

sudo apt-get dist-upgrade
