#!/bin/bash

mkdir -p ~/projects/oss
pushd ~/projects/oss
  git clone git@github.com:fgrehm/dotfiles.git && cd dotfiles && ./setup.sh && cd ..
  git clone git@github.com:fgrehm/vimfiles.git && cd vimfiles && ./setup.sh
popd
