#!/bin/bash

if [[ -f $HOME/bin/hub ]]; then
  echo 'Hub already installed, skipping'
  exit 0
fi

curl -L https://github.com/github/hub/releases/download/v2.2.1/hub-linux-amd64-2.2.1.tar.gz \
    | tar xvz -C /tmp

mv /tmp/hub-linux-amd64-2.2.1/hub $HOME/bin/hub
chmod +x $HOME/bin/hub
