#!/bin/bash

if ! [ -L /var/lib/lxc ]; then
  if [ -d /var/lib/lxc ]; then
    echo "Moving /var/lib/lxc to ${HOME}/lxc"
    sudo mv /var/lib/lxc ${HOME}
  else
    echo "Creating ${HOME}/lxc dir"
    mkdir -p ${HOME}/lxc
  fi
  echo "Symlinking /var/lib/lxc to ${HOME}/lxc"
  sudo ln -s ${HOME}/lxc /var/lib/lxc
else
  echo "Skipping /var/lib/lxc symlink"
fi

if ! [ -L /var/cache/lxc ]; then
  if [ -d /var/cache/lxc ]; then
    echo "Moving /var/cache/lxc to ${HOME}/lxc-cache"
    sudo mv /var/cache/lxc ${HOME}/lxc-cache
  else
    echo "Creating ${HOME}/lxc-cache dir"
    mkdir -p ${HOME}/lxc-cache
  fi
  echo "Symlinking /var/cache/lxc to ${HOME}/lxc-cache"
  sudo ln -s ${HOME}/lxc-cache /var/cache/lxc
else
  echo "Skipping /var/cache/lxc symlink"
fi

docker_runtime_path=${HOME}/docker
if ! $(grep -q ${docker_runtime_path} /etc/default/docker); then
  echo "Configuring docker to use ${docker_runtime_path} as the graph path"
  mkdir -p $docker_runtime_path
  echo "DOCKER_OPTS='-g ${docker_runtime_path}'" | sudo tee -a /etc/default/docker
else
  echo 'Skipping docker graph path config'
fi
