#!/bin/bash

sudo apt-get update
sudo apt-get dist-upgrade

sudo snap install hub --classic
sudo snap install docker --edge
sudo snap install slack --classic
sudo snap install spotify

sudo apt-get install --yes --force-yes \
  apt-transport-https \
  ca-certificates \
  curl \
  gawk \
  git \
  git-lfs \
  gnome-tweak-tool \
  gnupg-agent \
  htop \
  jq \
  openjdk-8-jre \
  parallel \
  tmux \
  tree \
  vim-gtk \
  vim-nox \
  virtualbox \
  xclip

sudo apt-get clean
sudo apt-get autoremove
