#!/bin/bash

sudo apt-get update
sudo apt-get dist-upgrade

sudo apt-get install --yes --force-yes \
  virtualbox-4.3 \
  nfs-kernel-server \
  dropbox \
  skype \
  gimp \
  curl tree htop \
  tmux \
  git gitg \
  vim-nox vim-gnome \
  icedtea-plugin \
  ubuntu-restricted-extras \
  lxc redir \
  google-chrome-stable \
  bsdtar \
  transmission \
  linux-image-extra-`uname -r` \
  asciinema \
  lxc-docker \
  p7zip \
  simplescreenrecorder \
  xclip

sudo apt-get clean
sudo apt-get autoremove
