#!/bin/bash

sudo apt-get update
sudo apt-get dist-upgrade

sudo apt-get install --yes --force-yes \
  nfs-kernel-server \
  dropbox \
  skype \
  gimp \
  curl tree htop \
  tmux \
  git \
  vim-nox vim-gnome \
  icedtea-plugin \
  ubuntu-restricted-extras \
  lxc redir \
  chromium-browser \
  bsdtar \
  transmission \
  linux-image-extra-`uname -r` \
  asciinema \
  p7zip \
  simplescreenrecorder \
  shutter \
  xclip \
  virtualbox \
  spotify-client \
  openjdk-7-jre-headless

curl -sSL https://get.docker.com/ | sh

sudo apt-get clean
sudo apt-get autoremove
