#!/bin/bash

curl -L https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip > /tmp/packer.zip
sudo mkdir -p /usr/local/packer
sudo unzip -d /usr/local/packer /tmp/packer.zip
echo 'export PATH="$PATH:/usr/local/packer"' >> $HOME/.bashrc
