#!/bin/bash

git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
mkdir -p ~/.rbenv/cache
mkdir -p ~/.rbenv/plugins
pushd ~/.rbenv/plugins
  git clone git://github.com/sstephenson/ruby-build.git
  git clone git://github.com/chriseppstein/rbenv-each.git
  git clone git@github.com:fgrehm/rbenv-install-remote.git
  git clone git://github.com/sstephenson/rbenv-vars.git
  git clone git://github.com/jamis/rbenv-gemset.git
popd

source ~/.bashrc

rbenv install 1.9.3-p327
VERSION_NAME=1.9.3-p327-patched rbenv install https://raw.github.com/gist/1688857/2-1.9.3-p327-patched.sh && rbenv global 1.9.3-p327-patched

rbenv rehash

rbenv each -v gem install rubygems-bundler bundler gem-browse
rbenv each -v gem regenerate_binstubs

gem install puppet puppet-lint tmuxinator

rbenv rehash
